apiVersion: v1
kind: Pod
metadata:
  name: demo-ssi-team7
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "[SSI-21/22][DEMO][SecuriteSystem] Team7 :) $i: $(date)"; i=$((i+1)); sleep 1; done']
